name: Python Nuitka Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.12.5]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build with Nuitka
      run: |
        nuitka --onefile --include-data-dir=resources=resources --include-data-file=resources/singbox.exe=resources/singbox.exe --show-scons --windows-uac-admin --user-package-configuration-file=nuitka-playwright.yml --output-dir=cache --standalone XBOXY/xboxy.py

    - name: Upload the build artifact
      uses: actions/upload-artifact@v4  # 上传构建产物
      with:
        name: xboxy-exe  # 产物名称
        path: cache/xboxy.exe  # 构建产物的路径
