name: Build_with_nuitka

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13.1
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        choco install 7zip --no-progress -y
        playwright install

    - name: Run PowerShell Commands
      shell: pwsh
      run: |
        nuitka --no-progressbar --assume-yes-for-downloads --playwright-include-browser=none --onefile --include-data-dir=resources=resources --include-data-file=resources/singbox.exe=resources/singbox.exe --windows-uac-admin --output-dir=cache --standalone xboxy.py
        mkdir output
        Copy-Item -Path "cache/xboxy.exe" -Destination "output/" -Recurse -Force
        7z a -t7z -mx=9 XBOXY.7z ./output/* -r

        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: XBOXY
        path: XBOXY.7z